---
baseURL: https://hugo-geekblog.geekdocs.de/
title: Geekblog
theme: hugo-geekblog
pygmentsUseClasses: true
pygmentsCodeFences: true
enableGitInfo: true
timeout: 180000

paginate: 5

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  author: authors
  tag: tags

mediaTypes:
  "application/atom+xml":
    suffixes:
      - "xml"

outputFormats:
  Atom:
    # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
    name: "Atom"
    mediaType: "application/atom+xml"
    # generated file: <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
    baseName: "feed"
    isPlainText: false
    rel: "alternate"
    isHTML: false
    noUgly: true
    permalinkable: false
  Json:
    # https://www.jsonfeed.org/2020/08/07/json-feed-version.html
    name: "Json"
    mediaType: "application/json"
    # generated file: <baseName>.<mediaType."application/feed+json".suffixes[0]> = feed.json
    baseName: "feed"
    isPlainText: false
    rel: "alternate"
    isHTML: false
    noUgly: true
    permalinkable: false

outputs:
  home:
    - HTML
    - ATOM
    - JSON
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML
    - ATOM
    - JSON

enableRobotsTXT: true

params:
  subtitle: Subtitle to describe your blog
  description: >
    hugo-geekblog is a simple Hugo theme for personal blogs. This page is theme documentation
    and powered by the latest version of hugo-geekblog itself.
  images:
    - "favicon/android-chrome-512x512.png"

  geekblogToC: 3
  geekblogAuthor: john-doe

  geekblogLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  geekblogPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy
